#sudo docker-compose up -d
#sudo docker-compose down
#sudo docker-compose ps
#docker stop cose_pronte_nodejs_1
#docker logs cose_pronte_nodejs_1

version: '3'

services:
    couchdb:
        image: couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpass
        ports:
            - 5984:5984
        volumes:
            - ./volumes/couchdb:/opt/couchdb/data
        restart: on-failure

        
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=adminpass
        ports:
            - 5432:5432
        volumes:
            - ./volumes/postgres:/var/lib/postgresql/data
        restart: on-failure


    rabbitmq:
        image: rabbitmq:3
        hostname: my-rabbit
        ports:
            - 5672:5672
        restart: on-failure


    nodejs:
        image: node
        working_dir: /usr/src/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./nodejs:/usr/src/app/
        ports:
            - 3000:3000
        depends_on:
            - couchdb
            - rabbitmq
        command: "node totale.js"
        restart: on-failure
        

#    php:
#        build:
#            context: ./docker/php
#        ports:
#            - 9000:9000
#        volumes:
#            - ./nginx:/srv/www/api
#            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
#        environment:
#            MYSQL_USER: user
#            MYSQL_PASSWORD: password


#    web_server:
#        image: nginx:1.13.8
#        ports:
#            - 8080:80
#        volumes:
#            - ./nginx:/srv/www/api
#            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#        depends_on:
#            - app_server
#            - mysql
#            - php
#        restart: on-failure
    
